apiVersion: apps.oms.ibm.com/v1beta1
kind: OMEnvironment
metadata:
  name: oms
  namespace: oms
spec:
  networkPolicy:
    podSelector:
      matchLabels:
        none: none
  security: {}
  license:
    accept: true
    acceptCallCenterStore: true  
  common:
    appServer:
      ports:
        http: 9080
        https: 9443
    ingress:
      host: console-openshift-console.apps-crc.testing # Set it to either the OpenShift host url (crc console --url) or the Minikube hostname (minikube).
      className: # Setting is not required if using OpenShift as Ingress Controller is configured  with default IngressClass. If using Minikube, Ingress has to enabled to activate IngressController and the corresponding IngressClass need to be provided. The name is usually nginx.
      ssl:
        enabled: false
    jwt:
       algorithm: RS512
       audience: service
       issuer: oms
  serverProfiles:
    - name: appserverprofile
      resources:
        limits:
          cpu: '2'
          memory: 3072Mi
        requests:
          cpu: '1'
          memory: 1024Mi
    - name: agentserverprofile
      resources:
        limits:
          cpu: '2'
          memory: 1024Mi
        requests:
          cpu: '1'
          memory: 512Mi
  upgradeStrategy: RollingUpdate
  secret: oms-secret
  serverProperties:
    customerOverrides:
      - derivatives:
          - groupName: AppServerProperties
            propertyList:
              yfs.USER_HOME: '${HOME}'
              yfs.yfs.YFS_ORDER_AUDIT.batchsize: '50'
              yfs.yfs.promotionrules.cache.disabled: 'N'
              yfs.yfs.pricelistheader.cache.disabled: 'N'
              yfs.yfs.YFS_ORDER_AUDIT_LEVEL.batchsize: '50'
              yfs.yfs.YFS_ORDER_LINE_SCHEDULE.batchsize: '50'
              yfs.osi.archive.order.additional.parts: YFS_ORDER_RELEASE
              yfs.osi.archive.order.part.YFS_ORDER_RELEASE.name: ordRel
              yfs.yfs.YFS_ORDER_LINE.batchsize: '50'
              yfs.yfs.YFS_ORDER_AUDIT_DETAIL.batchsize: '50'
              yfs.yfs.YFS_SHIPMENT_LINE.batchsize: '50'
              yfs.yfs.YFS_AUDIT.batchsize: '50'
          - groupName: AgentProperties
            propertyList:
              yfs.EXCEPTION_MONITOR_SERVER: EXCEPTION_MONITOR
              yfs.CREATE_SALES_ORDER: CREATE_SALES_ORDER
              yfs.oms_qcf: OMQueueManager
              yfs.yfs.flow.override.qcf: OMQueueManager
              yfs.yfs.agent.override.icf: com.sun.jndi.fscontext.RefFSContextFactory
              yfs.yfs.ItemProperties.cache.disable: 'Y'
              yfs.yfs.agent.override.qcf: OMQueueManager
              yfs.yfs.flow.override.providerurl: 'file:/opt/ssfs'
              yfs.yfs.promotionrules.cache.disabled: 'Y'
              yfs.yfs.pricelistheader.cache.disabled: 'Y'
              yfs.oms_provider_url: 'file:/opt/ssfs'
              yfs.yfs.agent.override.providerurl: 'file:/opt/ssfs'
              yfs.yfs.flow.override.icf: com.sun.jndi.fscontext.RefFSContextFactory
        groupName: BaseProperties
        propertyList:
          logService.systemlogger.logfilename: /shared/logs/system.log
          logService.systemlogger.sysout: /shared/logs/noapp.log
          yfs.jwt.create.audience: oserv
         # yfs.osi.archive.enabled: 'true'
         # yfs.ssi.log.request.and.response: 'Y'
          yfs.yfs.logall: 'Y'
          yfs.yfs.searchIndex.rootDirectory: /shared
          #yfs.yfs.ssi.enabled: 'Y'
          yfs.jwt.create.issuer: oms
          yfs.jwt.create.pk.alias: oserv
          yfs.jwt.create.algorithm: RS256
    jvmArgs:
      - groupName: JVMArguments
        propertyList:
          - '-DLOG_DIR=${LOG_DIR}'
          - '-DWLP_OUTPUT_DIR=${LOG_DIR}'
          - '-DJVM=${OM_POD_NAME}'
          - '-DIBM_LOG_FILE=ibmlog'
    envVars:
      - groupName: EnvironmentVariablesAppServer
        propertyList:
          JVM: ${OM_POD_NAME}
          LOG_DIR: /shared/logs/${OM_POD_NAME}
          LIBERTY_LOG_DIR: /shared/logs/${OM_POD_NAME}
          MESSAGE_FILE_NAME: ${LOG_DIR}/${OM_POD_NAME}_message.log
          TRACE_FILE_NAME: ${LOG_DIR}/${OM_POD_NAME}_trace.log
          TZ: America/New_York
      - groupName: EnvironmentVariablesAgent
        propertyList:
          JVM: ${OM_POD_NAME}
          LOG_DIR: /shared/logs/${OM_POD_NAME}
          LIBERTY_LOG_DIR: /shared/logs/${OM_POD_NAME}
          MESSAGE_FILE_NAME: ${LOG_DIR}/${OM_POD_NAME}_message.log
          TRACE_FILE_NAME: ${LOG_DIR}/${OM_POD_NAME}_trace.log
          TZ: America/Pittsburgh 
  serviceAccount: default
  image:
    pullPolicy: Always
    imagePullSecrets:
      - name: ibm-entitlement-key
    oms:
      agentDefaultName: om-agent
      appDefaultName: om-app
      pullPolicy: IfNotPresent
      repository: cp.icr.io/cp/ibm-oms-enterprise
      tag: 10.0.2403.2-amd64
  jms:
    mq:
      bindingConfigName: om-mqbindings
  dataManagement:
   mode: create
  database:
    db2:
      dataSourceName: jdbc/OMDB
      host: 9.30.211.182
      name: OMDB
      port: 50000
      schema: OMDB
      secure: false
      user: db2inst1
  storage:
    accessMode: ReadWriteMany
    capacity: 10Gi
    storageClassName: oms-nfs-storage  
    name: oms-pv
    securityContext:
      supplementalGroups:
        - 0
        - 1000
        - 1001
